name:Gh-Pages-Staging

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubunty-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v3
